Refactor warning disabling for Emscripten and Clang (#12585)
Updated warning disabling for compilers and removed conditional check
for WASM.

Otherwise it breaks for me on Tahoe 26.4 with latest xcode.

```
In file included from /Volumes/workplace/yaspar-org/yaspar-ir/target/debug/build/cvc5-sys-a5416e237358a5dd/out/cvc5/build/deps/src/Poly-EP/src/polyxx/algebraic_number.cpp:1:
  In file included from /Volumes/workplace/yaspar-org/yaspar-ir/target/debug/build/cvc5-sys-a5416e237358a5dd/out/cvc5/build/deps/src/Poly-EP/include/polyxx/algebraic_number.h:6:
  In file included from /Volumes/workplace/yaspar-org/yaspar-ir/target/debug/build/cvc5-sys-a5416e237358a5dd/out/cvc5/build/deps/src/Poly-EP/include/polyxx/dyadic_interval.h:6:
  In file included from /Volumes/workplace/yaspar-org/yaspar-ir/target/debug/build/cvc5-sys-a5416e237358a5dd/out/cvc5/build/deps/src/Poly-EP/include/polyxx/dyadic_rational.h:6:
  In file included from /Volumes/workplace/yaspar-org/yaspar-ir/target/debug/build/cvc5-sys-a5416e237358a5dd/out/cvc5/build/deps/src/Poly-EP/include/polyxx/integer.h:3:
  /Volumes/workplace/yaspar-org/yaspar-ir/target/debug/build/cvc5-sys-a5416e237358a5dd/out/cvc5/build/deps/include/gmpxx.h:2163:29: error: identifier '_mpz' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
   2163 | inline mpz_class operator"" _mpz(const char* s)
        |                  ~~~~~~~~~~~^~~~
        |                  operator""_mpz
  /Volumes/workplace/yaspar-org/yaspar-ir/target/debug/build/cvc5-sys-a5416e237358a5dd/out/cvc5/build/deps/include/gmpxx.h:2168:29: error: identifier '_mpq' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
   2168 | inline mpq_class operator"" _mpq(const char* s)
        |                  ~~~~~~~~~~~^~~~
        |                  operator""_mpq
  /Volumes/workplace/yaspar-org/yaspar-ir/target/debug/build/cvc5-sys-a5416e237358a5dd/out/cvc5/build/deps/include/gmpxx.h:2175:29: error: identifier '_mpf' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
   2175 | inline mpf_class operator"" _mpf(const char* s)
        |                  ~~~~~~~~~~~^~~~
        |                  operator""_mpf
  3 errors generated.
  make[6]: *** [src/CMakeFiles/static_pic_polyxx.dir/polyxx/algebraic_number.cpp.o] Error 1
  make[5]: *** [src/CMakeFiles/static_pic_polyxx.dir/all] Error 2
  make[4]: *** [src/CMakeFiles/static_pic_polyxx.dir/rule] Error 2
  make[3]: *** [static_pic_polyxx] Error 2
```

Signed-off-by: Jason Hu <zhonhu@amazon.com>