Bump CMS to 5.11.21 (#10317)
This PR bumps CMS from 5.8.0 to 5.11.21.

This is because with a sufficiently modern compiler, I'm hitting this
issue in CMS:

```
In file included from /home/avj/clones/cvc5/build/deps/src/CryptoMiniSat-EP/src/ccnr.cpp:23:
/home/avj/clones/cvc5/build/deps/src/CryptoMiniSat-EP/src/ccnr.h:103:24: error: ‘uint32_t’ has not been declared
  103 |     void set_verbosity(uint32_t verb);
      |                        ^~~~~~~~
/home/avj/clones/cvc5/build/deps/src/CryptoMiniSat-EP/src/ccnr.h:120:12: error: ‘uint8_t’ was not declared in this scope
  120 |     vector<uint8_t> _solution;
      |            ^~~~~~~
/home/avj/clones/cvc5/build/deps/src/CryptoMiniSat-EP/src/ccnr.h:29:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
   28 | #include "ccnr_mersenne.h"
  +++ |+#include <cstdint>
   29 |
```

This is was already fixed in CMS in commit:

-
https://github.com/msoos/cryptominisat/commit/03545f33f25a3635e15237c292972812e8608e21

Note, this PR removes the patch command which was applying the content
of this diff:

-
https://github.com/msoos/cryptominisat/commit/ba6f76e353c2b235131f0357eeea057b597c9d08

but that change got merged into 5.11.2 (and is therefore included in
5.11.21).

Signed-off-by: Andrew V. Teylu <andrew@tey.lu>